server.port=8080
spring.application.name=document-management-service
# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.connection.isolation=java.sql.Connection.TRANSACTION_READ_COMMITTED
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.default_schema=document_schema
# Datasource
spring.datasource.username=api
spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://${db_host:localhost}:5432/challenge?sslmode=disable&client_encoding=UTF8&tcpKeepAlive=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
# Logging
logging.level.root=debug
# Multipart
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
spring.servlet.multipart.file-size-threshold=0MB
# Minio
minio.url=http://${minio_host:localhost}:9000
minio.bucket=document-bucket
minio.access-key=admin
minio.secret-key=password