server.port=8080
spring.application.name=document-management-service
# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true
spring.jpa.properties.hibernate.jdbc.batch_size=${db_batch_size}
spring.jpa.properties.hibernate.connection.isolation=java.sql.Connection.TRANSACTION_READ_COMMITTED
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.default_schema=${db_schema}
# Datasource
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.datasource.url=${db_url}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.minimum-idle=${db_min_pool}
spring.datasource.hikari.maximum-pool-size=${db_max_pool
# Logging
logging.level.root=info
# Multipart
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
spring.servlet.multipart.file-size-threshold=0MB
# Minio
minio.url=${minio_url}
minio.bucket=${minio_bucket}
minio.access-key=${minio_access_key}
minio.secret-key=${minio_secret_key}